print("red")
print("blue")
print("green")
print("yellow")
print("purple")
print("orange")
print("black")
print("Road브랜치 추가")
print("clone다운-> 커밋 -> 푸쉬")
print("indigo")
print("white")
print("redwine")
print("핫픽스 반영")
print("리베이스 테스트 1")
